feat: add JSON representation for Marten::HTTP::UploadedFile (#328)
* feat: add JSON representation for Marten::HTTP::UploadedFile

This change introduces a `to_json` method to `Marten::HTTP::UploadedFile`,
allowing uploaded files to be included in JSON representations such as
`request.data.to_json`.

Previously, converting a request containing an uploaded file to JSON raised:

    Error: expected argument #1 to 'Marten::HTTP::UploadedFile#to_json' to be IO, not JSON::Builder

The new implementation defines `#to_json` and `#to_json(json : JSON::Builder)`,
returning an object with the following fields:
- `original_filename`
- `tempfile`
- `content_type`

This makes it possible to safely serialize uploaded files in request data.

* Remove the usage of content_type attribute in UploadFile